DEFAULT_MEDS = [
    # --- 1-KUN ---
    {
        "name": "Sho'rot rastoropshy",
        "dose": "1 osh qoshiq + 1 stakan issiq suv",
        "note": "1 oy",
        "time_slot": "morning",
        "time_label": "Bomdod (05:30)",
        "start_day": 1,
        "end_day": 30,
    },
    {
        "name": "Bleymaren",
        "dose": "1 tab → 0.5 litr suvda eritib huplayib",
        "note": "17:00 gacha tugatiladi. Ertalabki siydik pH ≥6.5 bo'lsa o'sha kuni ichilmaydi.",
        "time_slot": "morning",
        "time_label": "Bomdod (05:30)",
        "start_day": 1,
        "end_day": 120,
    },
    {
        "name": "Kolostruum + Metabiotik Anagran",
        "dose": "1 marta, surtish",
        "note": "Ovqatdan 1 soat oldin, 4 oy",
        "time_slot": "before_breakfast",
        "time_label": "Nonushta oldin 1 soat (07:00)",
        "start_day": 1,
        "end_day": 120,
    },
    {
        "name": "Metafungin Anagran",
        "dose": "1 ta",
        "note": "1 oy",
        "time_slot": "breakfast",
        "time_label": "Nonushta vaqtida (07:30)",
        "start_day": 1,
        "end_day": 30,
    },
    {
        "name": "Lypo Gold",
        "dose": "2 ta × 3 mahal (nonushta, tushlik, kechki ovqat)",
        "note": "4 oy",
        "time_slot": "breakfast",
        "time_label": "Nonushta vaqtida (07:30)",
        "start_day": 1,
        "end_day": 120,
    },
    {
        "name": "Lypo Gold (tushlik)",
        "dose": "2 ta",
        "note": "4 oy",
        "time_slot": "afternoon",
        "time_label": "Tushlik (13:00)",
        "start_day": 1,
        "end_day": 120,
    },
    {
        "name": "Lypo Gold (kechki ovqat)",
        "dose": "2 ta",
        "note": "4 oy",
        "time_slot": "dinner",
        "time_label": "Kechki ovqat (19:00)",
        "start_day": 1,
        "end_day": 120,
    },
    {
        "name": "Levotsetirizin 5 mg",
        "dose": "1 ta",
        "note": "Ovqatdan keyin, 5 oy",
        "time_slot": "evening",
        "time_label": "Kechqurun ovqatdan keyin (20:00)",
        "start_day": 1,
        "end_day": 150,
    },
    {
        "name": "Gallavit svechi 50 mg",
        "dose": "1 ta (orqa)",
        "note": "2 marta/kun, 20 kun ich + 10 kun dam. 4 oy sikl",
        "time_slot": "before_dinner",
        "time_label": "Kechki ovqat oldin (17:00)",
        "start_day": 1,
        "end_day": 120,
    },
    # Kapelnitsa 1-10 kun
    {
        "name": "Kokarbakosilaza 50 mg (kapelnitsa)",
        "dose": "t.i.",
        "note": "Kapelnitsa, kun 1-yarmi, tuk qoringa, shifokor nazoratida",
        "time_slot": "injection",
        "time_label": "Kapelnitsa (09:00)",
        "start_day": 1,
        "end_day": 10,
    },
    {
        "name": "Riboflavin 1.0 (kapelnitsa)",
        "dose": "m.o.",
        "note": "Kapelnitsa, kechqurun, 10 kun",
        "time_slot": "injection",
        "time_label": "Kapelnitsa (09:00)",
        "start_day": 1,
        "end_day": 10,
    },
    {
        "name": "L-Lizin Estsinat + Natriy tiosulfat + Kalsiy glyukonat + Vit C (kap.)",
        "dose": "Kapelnitsa sxemasi bo'yicha",
        "note": "1, 2, 3-kunlari t.i.",
        "time_slot": "injection",
        "time_label": "Kapelnitsa (09:00)",
        "start_day": 1,
        "end_day": 3,
    },
    # --- 2-KUN ---
    {
        "name": "Molibden 500 mkg (Seeking Health)",
        "dose": "1 ta",
        "note": "Ovqatdan keyin, kechqurun, 4 oy",
        "time_slot": "evening",
        "time_label": "Kechqurun ovqatdan keyin (20:00)",
        "start_day": 2,
        "end_day": 120,
    },
    {
        "name": "Tsink Karnozin (Dr.Best / Life Extension)",
        "dose": "2 ta",
        "note": "Ovqatdan 40 daqiqa oldin, ertalab, 5 oy",
        "time_slot": "before_breakfast",
        "time_label": "Nonushta oldin 40 daqiqa (07:00)",
        "start_day": 2,
        "end_day": 150,
    },
    # --- 3-KUN ---
    {
        "name": "Kalsiy tsitrat 1000",
        "dose": "2 osh qoshiq",
        "note": "Kechqurun ovqat oldin, 3 oy",
        "time_slot": "before_dinner",
        "time_label": "Kechki ovqat oldin (17:00)",
        "start_day": 3,
        "end_day": 90,
    },
    {
        "name": "Gl Repair (Anagran)",
        "dose": "2 ta × 2 mahal",
        "note": "Ovqat bilan birga, 2 oy. Keyin Intrinza",
        "time_slot": "breakfast",
        "time_label": "Nonushta vaqtida (07:30)",
        "start_day": 3,
        "end_day": 60,
    },
    {
        "name": "Gl Repair (Anagran) — tushlik",
        "dose": "2 ta",
        "note": "Ovqat bilan, 2 oy",
        "time_slot": "afternoon",
        "time_label": "Tushlik (13:00)",
        "start_day": 3,
        "end_day": 60,
    },
    {
        "name": "Intrinza (D'Adamo)",
        "dose": "2 ta × 2 mahal",
        "note": "Ovqat vaqtida, 3 oy (Gl Repair tugagandan keyin)",
        "time_slot": "breakfast",
        "time_label": "Nonushta vaqtida (07:30)",
        "start_day": 61,
        "end_day": 150,
    },
    # --- 4-6-8-10-12 kun kapelnitsa ---
    {
        "name": "Gepamerts + Elkar (kapelnitsa)",
        "dose": "Gepamerts 10.0 + NaCl 200ml; 2 soat sekin tomchilab",
        "note": "4, 6, 8, 10, 12-kunlari",
        "time_slot": "injection",
        "time_label": "Kapelnitsa (09:00)",
        "start_day": 4,
        "end_day": 12,
    },
    {
        "name": "Norogrizovim 1.0+2.0 (mushak ichiga)",
        "dose": "m.o.",
        "note": "4, 8, 12, 15, 18-kunlari, kechqurun",
        "time_slot": "im",
        "time_label": "Mushak ichiga (19:30)",
        "start_day": 4,
        "end_day": 18,
    },
    # --- 5-7-9-11-13 kun kapelnitsa ---
    {
        "name": "Reamberin + Geptral + TAD/Glutaion + Vit C + B6 + Essensialy (kap.)",
        "dose": "Kapelnitsa sxemasi bo'yicha",
        "note": "5, 7, 9, 11, 13-kunlari t.i.",
        "time_slot": "injection",
        "time_label": "Kapelnitsa (09:00)",
        "start_day": 5,
        "end_day": 13,
    },
    # --- 7-KUN ---
    {
        "name": "Rejuvenzyme (Source Naturals)",
        "dose": "2 ta",
        "note": "Ovqatdan 40 daqiqa oldin, 3 oy",
        "time_slot": "before_breakfast",
        "time_label": "Nonushta oldin 40 daqiqa (07:00)",
        "start_day": 7,
        "end_day": 97,
    },
    # --- 8-KUN ---
    {
        "name": "Taurin 1000 mg",
        "dose": "1 ta",
        "note": "Kechqurun ovqat oldin, 2 oy",
        "time_slot": "before_dinner",
        "time_label": "Kechki ovqat oldin (17:00)",
        "start_day": 8,
        "end_day": 68,
    },
    # --- 9-KUN ---
    {
        "name": "Liposomal Vitamin A Anagran sprey",
        "dose": "1 marta og'izga sepish",
        "note": "Kechqurun ovqat vaqtida, 3 oy",
        "time_slot": "dinner",
        "time_label": "Kechki ovqat (19:00)",
        "start_day": 9,
        "end_day": 99,
    },
    {
        "name": "Vitamin D3+K2 5000",
        "dose": "1 ta",
        "note": "Ovqatdan keyin, doimo",
        "time_slot": "evening",
        "time_label": "Kechqurun ovqatdan keyin (20:00)",
        "start_day": 9,
        "end_day": 9999,
    },
    # --- 10-KUN ---
    {
        "name": "Glutamin 5g (Jarrow poroshok)",
        "dose": "1 ch.q. (5 g)",
        "note": "Ertalab ovqatdan 50 daqiqa oldin, 1 yil",
        "time_slot": "before_breakfast",
        "time_label": "Nonushta oldin 50 daqiqa (07:00)",
        "start_day": 10,
        "end_day": 365,
    },
    {
        "name": "Betain xlor",
        "dose": "Individual (1 kapsuldan boshlash, qizish hissigacha oshirish)",
        "note": "Har 3 mahal ovqat bilan. Qizish hissida 1 ga qaytariladi. 6 oy–1 yil",
        "time_slot": "breakfast",
        "time_label": "Nonushta vaqtida (07:30)",
        "start_day": 10,
        "end_day": 365,
    },
    # --- 12-KUN ---
    {
        "name": "Omega-3 с имбирём (Anagran)",
        "dose": "1 ta",
        "note": "Ovqat vaqtida, 3 oy",
        "time_slot": "dinner",
        "time_label": "Kechki ovqat (19:00)",
        "start_day": 12,
        "end_day": 102,
    },
    # --- Kapelnitsa tugagandan keyin (taxminan 14-kun) ---
    {
        "name": "Vitamin C / Natriy askorbat 500",
        "dose": "1 ta",
        "note": "Ertalab ovqatdan 30 daqiqa oldin, 3 oy (kapelnitsa tugagandan keyin)",
        "time_slot": "before_breakfast",
        "time_label": "Nonushta oldin (07:00)",
        "start_day": 14,
        "end_day": 104,
    },
]
